/*----------------------------------------------------------------------------------------------------------------------------------------
    * Apex Class Name: RatePlannerTriggerHelper
    * Version:         1.0
    * Created Date:    03/04/2024
    * Function:        Trigger Helper of RatePlannerTriggerHandler
----------------------------------------------------------------------------------------------------------------------------------------*/
public with sharing class RatePlannerTriggerHelper extends TriggerUtils {
    /***************************************
    *         Helper Operations           *
    ***************************************/


    public static void example(List<RatePlanner__c> lNew){

    }
}
