/*-------------------------------------------------------------------------------------------------------------------------------------------------------
Author:         Santiago Cividanes
Company:        Devoteam
Description:    Controller Apex Class for the gL_familyList LWC

History:
<Date>                  <Author>                <Change Description>
21/03/2022              Santiago Cividanes		Initial Version
--------------------------------------------------------------------------------------------------------------------------------------------------------*/
public with sharing class GL_FamilyListCtrl {

}