/**
 * @description  : 
 * @author       : Nubika Team <example@nubika.com>
 * @version      : 1.0.0
 * @date         : 13-02-2025
 * @group        : 
 * @see          :  
 * Modifications Log
 * Ver   Date         Author                             Modification
 * 1.0   13-02-2025   Nubika Team <example@nubika.com>   Initial Version
**/
public with sharing class testClass {
    public testClass() {
        String test = 'test';
    }
}
