/**
 * @description  : 
 * @author       : Nubika Team <example@nubika.com>
 * @version      : 1.0.0
 * @date         : 12-11-2024
 * @group        : 
 * @see          : 
**/
@isTest
public with sharing class TestDelta {
    public TestDelta() {
        System.debug('ey 4');
        System.debug('ey 5');
        System.debug('ey 6');
        System.debug('ey 7');
        System.debug('ey 8');
        System.debug('ey 9');
        System.debug('ey 10');
    }
}